import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { logger } from "../logger.js";

/**
 * Allowlist key yang boleh ditulis oleh setup wizard.
 * Penting untuk security — mencegah injection key arbitrary.
 */
export const ALLOWED_ENV_KEYS = [
  "NODE_ENV",
  "PORT",
  "KLIKQRIS_API_BASE",
  "KLIKQRIS_API_KEY",
  "KLIKQRIS_MERCHANT_ID",
  "TELEGRAM_BOT_TOKEN",
  "DISCORD_BOT_TOKEN",
  "DISCORD_CLIENT_ID",
  "DISCORD_GUILD_ID",
  "OWNER_TELEGRAM_ID",
  "OWNER_DISCORD_ID",
  "ADMIN_TELEGRAM_IDS",
  "ADMIN_DISCORD_IDS",
  "ADMIN_USERNAME",
  "ADMIN_PASSWORD",
  "ADMIN_SESSION_SECRET",
  "DATABASE_URL",
  "PUBLIC_BASE_URL",
] as const;

export type EnvKey = (typeof ALLOWED_ENV_KEYS)[number];

const ENV_PATH = resolve(process.cwd(), ".env");

/**
 * Baca .env saat ini dan return Map key→value.
 * Hanya parse baris valid `KEY=VALUE`. Comments & blank lines diabaikan.
 */
export function readEnvFile(): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(ENV_PATH)) return map;

  const content = readFileSync(ENV_PATH, "utf-8");
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    // Strip surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    map.set(key, value);
  }
  return map;
}

/**
 * Tulis .env dengan format rapi, group by section.
 * Backup .env lama ke .env.bak.<timestamp> kalau ada.
 */
export function writeEnvFile(values: Map<string, string>): { backupPath: string | null } {
  let backupPath: string | null = null;
  if (existsSync(ENV_PATH)) {
    backupPath = `${ENV_PATH}.bak.${Date.now()}`;
    copyFileSync(ENV_PATH, backupPath);
  }

  const get = (k: EnvKey) => values.get(k) ?? "";

  const content = `# Generated by botnot setup wizard at ${new Date().toISOString()}
# Edit manually anytime — wizard akan preserve format ini.

NODE_ENV=${get("NODE_ENV") || "development"}
PORT=${get("PORT") || "3000"}

# === KlikQRIS ===
KLIKQRIS_API_BASE=${get("KLIKQRIS_API_BASE") || "https://klikqris.com/api"}
KLIKQRIS_API_KEY=${get("KLIKQRIS_API_KEY")}
KLIKQRIS_MERCHANT_ID=${get("KLIKQRIS_MERCHANT_ID")}

# === Telegram ===
TELEGRAM_BOT_TOKEN=${get("TELEGRAM_BOT_TOKEN")}

# === Discord ===
DISCORD_BOT_TOKEN=${get("DISCORD_BOT_TOKEN")}
DISCORD_CLIENT_ID=${get("DISCORD_CLIENT_ID")}
DISCORD_GUILD_ID=${get("DISCORD_GUILD_ID")}

# === Owner (primary admin yg dapet notifikasi event penting) ===
OWNER_TELEGRAM_ID=${get("OWNER_TELEGRAM_ID")}
OWNER_DISCORD_ID=${get("OWNER_DISCORD_ID")}

# === Admin tambahan (CSV user IDs) ===
ADMIN_TELEGRAM_IDS=${get("ADMIN_TELEGRAM_IDS")}
ADMIN_DISCORD_IDS=${get("ADMIN_DISCORD_IDS")}

# === Web Dashboard ===
ADMIN_USERNAME=${get("ADMIN_USERNAME")}
ADMIN_PASSWORD=${get("ADMIN_PASSWORD")}
ADMIN_SESSION_SECRET=${get("ADMIN_SESSION_SECRET") || generateSecret()}

# === Database ===
DATABASE_URL=${quoteIfNeeded(get("DATABASE_URL") || "file:./dev.db")}

# === Webhook ===
PUBLIC_BASE_URL=${get("PUBLIC_BASE_URL")}
`;

  writeFileSync(ENV_PATH, content, "utf-8");
  logger.info({ envPath: ENV_PATH, backupPath }, ".env updated by setup wizard");
  return { backupPath };
}

export function generateSecret(): string {
  return randomBytes(32).toString("hex");
}

function quoteIfNeeded(value: string): string {
  // SQLite URL pakai colon → quote untuk safety
  if (value.includes(":") || value.includes(" ")) return `"${value}"`;
  return value;
}
